### ISSUE TITLE
목탄님 추천

### ISSUE THREAD

**Issue by gidonyou** [gidonyou/MCPlugin_GameAge#1]
** 목탄님 추천**

플러그인의 지장을 주는
-> 플러그인의 쾌적한 이용에 지장을 주는

**Comment by gidonyou** [comment]
수정완료

**Comment by gidonyou** [comment]
**목탄님 추천**

## 밸런스 패치

### 드롭
- 다이아 칼 Pool : 10 --> 12
- 철  칼 Pool : 5 --> 3

> 다이아 칼 드랍률이랑
> 철칼 드랍률이 딱 두 배 차이나네요
> 다이아 3개에 철 12개 이렇게 해두는 게 더 낫지 않을까요

### 아이템

- 구급상자 --> 재생 효과로 변경 또는 쿨타임 추가

## 맞춤법

기본 칼 아래:  
'게임이 시작할 때'가 이게  
게임이 지 스스로 시작되고 그러는 게 아니라서

'게임이 시작될 때' 라던가 '게임을 시작할 때' 라고 하는 게 더 나을듯.

돌 칼 아래:  
'한 단계 업그레이드되었습니다' 가 올바름.


다이아 칼 아래:  
개인적으로는 '무기 중 가장 높은 데미지를 가지고 있습니다.'가 더 깔끔하고 좋은 것 같은데 물론 굳이 이렇게 안 써도 됨.


방패 아래:  
'자신을 방어할 때 이용합니다.' 가 올바르지만, 좀 더 구체적으로 설명하는 것도 좋을듯.  
가령 '상대의 공격으로부터~' 를 추가한다던가 하면 더 좋을 것 같음.

가르키는 나침판:  
'가르키는 -> 가리키는'

'자신보다 시간이 많이 남은' 또한 '자신보다'와 '시간'의 호응 관계가 약간 애매함.  
'자신보다 많은 시간을 가지고 있는' 과 같이 수정하면 좋을듯.  
아래의 '적은 시간 유저' 아이템 설명과 통일시키는 것도 좋은 생각임.

죽음의 책 아래:  
+ 다이아 칼 사진이 있는데, 저거 아무리 봐도 책같이 생겨먹지가 않았음. 사진 잘못 올라온 것 같음. 아마도...

붕대 아래:  
'최대'와 'HP'의 거리가 조금 멀음. '자신의 체력을 최대 2칸까지 치유합니다.' 라고 쓰면 좋을듯.

상대방 수명 뺏기:  
이거 ㄹㅇ 사기템 아님?  
...여튼

'지목 상대에서 시간을 뺏습니다' 보다는 '지목한 상대의 시간을 뺏습니다' 가 더 직관적일듯.

**Comment by gidonyou** [comment]
위키 수정 완료

**Comment by gidonyou** [comment]
1.0.0 으로 싹다 패치 #624ca68a9e7066ef4b35637317ad37ba69ea8fe0

**Comment by gidonyou** [comment]
< 아이템 드롭율 변경 제안 >
+ 아이템의 수(X개)에 초점을 맞추지 말고, 아이템의 드롭 확률(X.XX%)에 초점을 맞췄으면 좋겠습니다.


< 아이템 추가 제안 >
 공격 
+ 금 칼 : 상대 타격시 10(하트 5칸)의 데미지를 가하지만, 한 번 때리면 사라지는 아이템으로 구상해봤습니다.
방패가 사라진 이후에 왼손 슬롯에 놓고 쓸 수 있는 죽창과 같은 존재라고 볼 수 있겠네요. (아래에 가칭 'GOLD_SWORD'로 적어두었습니다.)

 방어 
+ 상대는 내게 공격을 가하지만, 나는 그럴 수 없는 비상 사태에서의 용이한 도주를 위해 다음 아이템 중 하나를 추가하면 좋겠습니다.
ex. 투명화 시계 / 1회성, 지속 시간 10초 또는 5초 (아래에 가칭 'INVISIBILITY_WATCH'로 적어두었습니다.)
ex. 엔더 진주 / 1회성 (아래에 가칭 'ENDER_PEARL'로 적어두었습니다.)

 유틸리티 
+ 1등을 위하여, 꼴지의 신상 정보만을 알려주는 아이템을 추가하면 좋겠습니다. (아래에 가칭 'PLAYER_LAST'로 적어두었습니다.)
+ 아무 사람의 등수를 "모두에게" 알리는 확률X망템을 추가해주셔도 좋습니다. gidonyou가 썼는데 gidonyou가 3등이라는 사실이 모두에게 전파될 수 있는 아주 좋은 아이템이죠. 모두에게 방송한다는 특징에 초점을 두어 음반 같은 아이템에 바인드하면 좋을 것 같습니다. (아래에 가칭 'SCOOP'으로 적어두었습니다.)




 종합 
+ 위에 열거된 아이템 추가 및, 다음과 같은 드롭 확률 재조정을 요청합니다.

 무기 아이템 
WOOD_SWORD : 0%
STONE_SWORD : 15%
IRON_SWORD : 8%
GOLD_SWORD(가칭) : 4%
DIAMOND_SWORD : 3%
SHIELD : 0%
(전체 비중의 30%)

 찾는 아이템 
LOCATION_FINDER : 5%
PLAYER_TIME_ABOVE : 8%
PLAYER_TIME_BELOW : 8%
PLAYER_LAST(가칭) : 6%
PLAYER_TIME_LIST : 3%
SCOOP(가칭) : 5%
(전체 비중의 35%)

 추가 아이템 
BANDAGE : 15%
FIRST_AID : 7%
INVISIBILITY_WATCH(가칭) : 2%
ENDER_PEARL(가칭) : 2%
(또는 위 두 개 아이템 중 하나의 드롭 확률 4%, 다른 하나는 0%)

EARN_SECONDS : 6%
STEAL_TARGET : 3%
(전체 비중의 35%)

**Comment by hyeonhigh** [comment]
+ 아 생각해보니 꼴찌를 꼴지라고 썼네요

알 게 뭐람 헿

**Comment by gidonyou** [comment]
@hyeonhigh

> 1등을 위하여, 꼴지의 신상 정보만을 알려주는 아이템을 추가하면 좋겠습니다. (아래에 가칭 'PLAYER_LAST'로 적어두었습니다.)

이렇게 된다면 꼴등은 모든사람에게 존재를 들키기 때문에 아이템 추가를 거부합니다. 하지만:
- 일등의 `PLAYER_TIME_ABOVE` 는 꼴지의 존재를 알려주고
- 꼴등의 `PLAYER_TIME_BELOW` 는 1등의 존재를 알려줍니다.

따라서 아이템 이름을 바꾸고 싶지만 생각이 안나네요;;
